Expose mutation testing report
trayio/mock-inspect pull request #37
Opened 2021-04-13 15:10 UTC by thomaschaplin

2021-04-13 15:55 UTC, thomaschaplin commented
As discussed with @rickschubert I shall look into moving this into a GitHub action as an artifact instead of living in the main repo. It can be run via a CRON - monthly maybe?

2021-04-13 16:01 UTC, rickschubert commented
@thomaschaplin I think weekly would be fine even, or twice a week.

2021-04-14 15:52 UTC, rickschubert approved these changes

2021-04-14 15:53 UTC, merged

2021-04-14 15:53 UTC, rickschubert requested changes
The path needs to change due to the rename

2021-04-14 15:53 UTC, rickschubert commented on README.md
> +[![Mutation badge](https://img.shields.io/badge/Mutation%20Coverage-88.93-green)](https://trayio.github.io/mock-inspect/reports/mutation/html/)
```suggestion
[![Mutation badge](https://img.shields.io/badge/Mutation%20Coverage-88.93-green)](https://trayio.github.io/mock-inspect/mutation/)
```